apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-jenkins-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learn-jenkins-app
  template:
    metadata:
      labels:
        app: learn-jenkins-app
    spec:
      template:
        spec:
          containers:
            - name: my-app
              image: ${IMAGE_NAME}  # 动态替换
              ports:
                - containerPort: 8080